---
title: "DAMNation Guide"
author: "Austin Montgomery"
date: "6/14/2021"
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_depth: 2
    number_sections: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---

```{=html}
<style type="text/css">
  body{
  font-size: 12pt;
}
</style>
```
# Documentation

## Description

DAMNation is a Shiny application used to analyze the raw data generated by TriKinetics Drosophila Activity Monitors (DAM). From this raw data, DAMNation can analyze locomotor activity, sleep, and even death for each specific fly involved in the experiment. These analyses results can be previewed in the app, downloaded as .csv files, and visualized as plots using user-configured settings.

## Contact Information

Austin Montgomery: austinbrucemontgomery\@gmail.com

Adrian Rothenfluh: adrian.rothenfluh\@hsc.utah.edu

## Source Code

Source code is available through the [DAMNation GitHub Repository](https://github.com/bigmonty12/DAMNation).

# Quick-Start Guide

1.  Upload standard DAM files from local computer
2.  Select the number of different conditions/genotypes combinations (i.e. wB exposed to EtOH & wB exposed to air would be 2 combinations)
3.  To label each condition/genotype, select the blue button (CONDITION/GENOTYPE \#). Type the condition/genotype in the first box.
4.  In this same dropdown menu, select which flies from each uploaded monitor file fits this condition/genotype.
5.  Repeat this process for each condition/genotype.
6.  Select the dates of the data you wish to analyze (NOTE: Important to adjust for ZT time. The last day selected should have an entire day's worth of data, not only a partial day's worth of data)
7.  Adjust the data bin length for which data was collected in the DAM file.
8.  Adjust the light onset time to match your experiment.
9.  Click the red Data Check button (If it is a success, continue. If there is an error, see the error guidance underneath).
10. Click the green Analyze Data button.
11. Preview the tables for each condition/genotype as a sanity check (Or just to see if something cool is obvious!)
12. On the left sidebar, select which of these tables to download as .csv files.
13. If interested in making quick visualizations, click on the Plot Results tab. Adjust the colors and other settings to create plots. After creating a plot, it is available to download.
14. Enjoy and feel free to offer any feedback through email or GitHub issues!

# Preprocess Data

## Download DAM Monitor Data

The first step in this analyses is to make sure the downloaded DAM experiments are in the correct format. This is is the point where one decides how often to bin the data, an important variable in analysis (as seen by [Dam Data Bins]). Make sure all files have the same starting point and ending point (at least if they are to be analyzed concurrently). 
Note that when downloading monitor data in DAMFileScan, make sure the final data bin collected is at least 2 hours past the experiment endpoint. This additional time is used to determine if flies are dead at the end of the experiment or not.

## Upload Monitor Files

DAMNation accepts DAM system monitor files in .txt format. If uploading multiple monitor files (CTRL-Click to select multiple files), make sure the starting date and time and the end date and time are the same for all files or there will be an error.

## Number of Conditions/Genotypes

While impractical, It is possible to have infinite conditions/genotypes. Simply type in how many you want. Click on the blue button underneath (CONDITION/GENOTYPE \#X), and type the desired name into the first box. Underneath the input name, each monitor file is available to select the flies that have the input condition/genotype. The default choices for each monitor are 1-32, 1-16, 17-32, and Manually Select. Note that choosing Manually Select essentially renders your choice as "No flies in this monitor match this condition" until clicking on the Channels dropdown box and selecting each fly.

## Dates of Experiment

Select the dates of the experiment you hope to analyze. DAMNation will remove all recorded data from before the Light Onset of the chosen first date. The first date is fairly straightforward to choose, but due to ZT time adjustments, it can be difficult to know which date to choose as the last date. I find it helpful to think of the last date as the last day where 24 hours of data were recorded.

For example, take a 3 day experiment that start on Jan 1st. While technically the experiment will end at the Light Onset time on Jan 4th, the last date with 24 hours of data is Jan 3rd. Thus, Jan 1st - Jan 3rd would be the dates selected for a three day experiment.

## DAM Data Bins {#dam-data-bins}

This setting is used to describe the sampling rate for the DAM file. The options are 1 min, 2 min, and 3 min due to how sleep is calculated (6 consecutive minutes of no beam breaks).

## Light Onset Time

Simply, Light Onset Time is what time the light turns on for the flies. It is used to establish ZT time.

## Data Check (Troubleshooting)

It is important to do a data sanity check by clicking on the red Data Check button.

If everything looks good, a Success! box with a check mark will appear.

If the full selected dates are not available in the data, a red Warning! box with an X will appear. This is most likely due choosing dates that are not available in the uploaded monitor files. Another possibility is that the DAM Data Bins parameter is different than what occurs in the data.

If there seems to have been an error during the experiment such that the monitor file says the DAM system turned off (status = 0), a Warning! box will occur. At this point, a dialogue box will say which files, dates, and (first 5 and last 5) times the DAM system was off. If it was only a small blip, then it should be okay to continue analyzing the data. More extensive issues may mean the experiment needs to be repeated or the selected dates for analysis need to be changed.

## Analyze Data

If the Data Check does not result in the Warning! screen, a green Analyze Data button will appear. Clicking on this button will start a Loading screen and end on the Preview Results tab after the analysis is completed.

# Preview Results

## Download

After analyzing the raw data, a Download button and dropdown box will appear on the left tab panel. As a default, all generated files will be downloaded, but this can be changed in the dropdown box. There are six generated files for each condition/genotype. After selecting the desired files, click the blue Download button to download the files to the user's computer.

Four of these six files (all but the Bouts files) can be previewed in the tables that appear in the main body of the app. Each set of tables has the condition/genotype label in the top right corner.

## Activity and Sleep Average Values

### *Time of Death*

Flies are determined to be dead based on no activity during the last two hours of the experiment and no activity after the experiment ends. This accounts for the light onset which usually causes an increase in fly activity. The greater amount of data after the experiment ends, the more likely the call of death is accurate. The actual time of death is found from the last time entry in the sleep bouts table. Note also that if a fly is declared dead, the default is to remove all the values in these summary tables.

Of course, this method of finding death is incredibly imprecise. Some flies are known to be very sluggish and could be labeled as dead when they are, in fact, just lazy. The DAM system doesn't provide the resolution needed to accurately call death (imaging/video would be necessary), so this is the algorithm we agreed upon.

### *Total Sleep*

Sleep is defined here as 6 or more minutes of no activity (zero beam breaks). Each bout of sleep is aggregated for each fly. Day Total sleep is defined as all the sleep that occurs during the entire experiment while the lights are on, while Night Total sleep is sleep that occurs while the light are off. Total Total sleep is every minute of sleep from the complete experiment.

### *Mean Sleep*

Mean sleep is simply the three values mentioned above (Day Total sleep, Night Total sleep, Total Total sleep) divided by the number of days analyzed in the experiment. It is the average minutes of sleep for each time period of each day.

### *Activity Average*

Activity Average is defined as the average number of beam breaks for each period. Total beam breaks for each period were summed for the entire experiment. Each period total beam breaks was then divided by the total number of days analyzed in the experiment.

### *Activity Rate*

Activity Rate is defined as the number of beam breaks per minute awake. This is calculated by summing up the total number of beam breaks for each period for the entire experiment. These figures were then divided by the total number of minutes awake for each period for the entire experiment. The total number of minutes awake was calculated by subtracting the [total sleep] values from the total time during that period (60 \* 12 (or 24) \* number of days)

## Activity and Sleep Daily Values

### *Date Total Sleep*

Total Sleep in this table is the total number of minutes asleep for the date shown in the column. For each day of the analyzed experiment, there will be a column with the date and the total minutes of sleep for that date.

### *Date Sleep Latency*

Sleep Latency is defined as the number of minutes it takes for a fly to fall asleep after the lights turn off. If a fly is already asleep before the light turns off, the sleep latency value will be 0 minutes. This follows the same format as [Date Total Sleep] where there is a column and value for each date in the analyzed experiment.

## Sleep Average by Hour of Day

This table includes the average number of minutes of sleep for each hour of the day. Thus, there will be 24 values for each fly in the experiment.

## Average Beam Breaks by Hour of Day

Similar to [Sleep Average by Hour of Day], this table includes 24 values for each fly in the experiment. Each value represents the average number of beam breaks for that specific hour of the day.

## Bouts

The bouts table contains information on each bout of sleep for each fly. This table can be a bit complicated on initial view. Each fly has four columns. The first column is the time and date of the beginning of a bout of sleep. The second column is the time and date of the end of a bout of sleep. The third column is the number of minutes of the bout of sleep. The fourth column designates whether the bout of sleep occurs during lights on or lights off.

## Bout Averages

The bout averages table finds summary statistics for the bouts of each fly. It finds the total number of bouts, the mean length of bout, and the standard deviation of bout length for both lights on and lights off.

# Plot Results

While these plots may not be publication-ready, they provide a great way to quickly see what happened in your experiment. Each plot can also be downloaded if needed as a guide to make a better figure or to include in a last minute presentation.

## Variable to Plot

Each of the variables from the previously previewed data tables is available to plot. The variables are grouped by the name of the table in which it appears. Some variables only have specific plots available (i.e. Only a Mortality plot can be used with the variable Death Time)

## Color

Each condition/genotype can have its own color. The color picker allows the user to pick very specific colors.

## Plot Type

As noted in [Variable to Plot], not every plot type is available for each variable. Mortality plots are only available for Death Time. Box, violin, bar, and density plots are available for variables (except Death Time) in the [Activity and Sleep Average Values] table. Box, violin, line, and bar plots are available for variables in the [Activity and Sleep Daily Values] table. Only a line plot is available for [Sleep Average by Hour of Day] and [Average Beam Breaks by Hour of Day].

## Add Data Points

Adding the actual data points can be very useful for illustrating how the data is distributed. While this option can always be toggled between Yes and No, there are certain plots which cannot show individual data points.

## Display SEM Bars

The SEM bars are generated with the data's mean +- the standard error. Similar to [Add Data Points], certain plots will not display SEM bars despite the option being toggled to Yes.

# Examples

## One file, Two Conditions/Genotypes

<iframe width="560" height="315" src="https://www.youtube.com/embed/A8aGMYSVp6s" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1">

</iframe>

In the example above, we want to analyze an experiment for three days. Only one monitor file is uploaded. This monitor had two different conditions, A and B. The first 16 flies were condition A, and the last 16 flies (17-32) were condition B. After clicking the Data Check button and receiving the success response, we can now click the Analyze Data button.

## Three files, Two Conditions/Genotypes

<iframe width="560" height="315" src="https://www.youtube.com/embed/U6ARcATH98Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1">

</iframe>

In the example above, we now want to analyze three monitor files for three days of an experiment. We use the CTRL-button to select multiple files. Once again, there are only two conditions, A and B. The entire first monitor and the first half of the second monitor are condition A. The entire third monitor and the second half of the second monitor are condition B. Note that if a condition is not present in a monitor, we click 'Manually Select" to default to 0 flies selected.

# Acknowledgements

The authors would like to acknowledge the critical feedback and guidance of members of the Aylin Rodan, MD, PhD lab and members of the Adrian Rothenfluh, PhD lab. Specifically, Maggie Chvilicek, Travis Philyaw, Masa Miscevic, and Emily Nickel helped drive this project forward with their suggestions and usage.
